---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
  labels:
    app: mediawiki-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki-app
  template:
    metadata:
      labels:
        app: mediawiki-app
    spec:
      # volumes:
      #   - name: secret-vol
      #     secretName: mysqlsec
      containers:
      - name: mediawiki
        image: mediawiki
        envFrom:
          - secretRef:
              name: mysqlsec

        ports:
          - name: mediawiki-port
            containerPort: 80
            protocol: TCP
