apiVersion: v1
kind: Service
metadata:
  name: mediawiki
spec:
  type: NodePort
  selector:
    app: mediawiki-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31840
