---
apiVersion: v1
kind: ConfigMap
metadata:
  name: initdb
data:
  initdb.sql: |
    CREATE USER 'wiki'@'%' IDENTIFIED BY 'mysqladmin';
    CREATE DATABASE wikidatabase;
    GRANT ALL PRIVILEGES ON wikidatabase.* TO 'wiki'@'%';
    FLUSH PRIVILEGES;